app = "sublinkx"
primary_region = "hkg"

[env]
  PORT = "8080"

[mounts]
  source = "sublink_data"
  destination = "/app/db"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = "10s"
    path = "/"
    timeout = "2s"